const sizes={post:['منشور 4:5',1080,1350],story:['ستوري/Reels',1080,1920],square:['مربع',1200,1200],wide:['أفقي',1280,720]};
const tabs=[['content','المحتوى'],['image','الصورة'],['title','العنوان'],['badge','عاجل'],['logo','الشعار'],['colors','الألوان'],['templates','القوالب'],['sizes','المقاسات'],['library','المكتبة'],['admin','الإدارة']];
const templates=[['classic','قالب علوي','صورة علوية + شريط عنوان سفلي'],['full','خلفية كاملة','صورة كاملة + طبقة داكنة + عنوان كبير'],['strip','شريط عاجل','صورة رئيسية + شريط سفلي قوي']];
const fonts=['Cairo','Tajawal','IBM Plex Sans Arabic','Noto Kufi Arabic','Noto Sans Arabic'], badges=['عاجل','خبر عاجل','تنبيه','حصري','عاجل جدًا','نص مخصص'];
let state={tab:'content',zoom:.44,media:[],logos:[],saved:'غير محفوظ',title:'مصادر تؤكد تطورات عاجلة في ملف اقتصادي مهم خلال الساعات القادمة',alt:'وصف مختصر للصورة والخبر',newsType:'سياسة',size:'post',template:'classic',image:'',imageZoom:1,imageX:50,imageY:50,overlay:32,font:'Cairo',fontSize:76,weight:900,lineHeight:1.12,align:'right',textColor:'#ffffff',autoFit:true,badgeShow:true,badgeText:'عاجل',badgePreset:'عاجل',badgeBg:'#e50914',badgeColor:'#ffffff',badgeSize:1,badgeX:76,badgeY:74,logoShow:true,logo:'',logoSize:1,logoX:780,logoY:70,logoOpacity:1,bg:'#07111f',grad:'#b70010',pattern:'grid',gradPower:74,exportType:'png',quality:.94};
const root=document.getElementById('root');
const set=p=>{Object.assign(state,p,{saved:'تغييرات غير محفوظة'});render()};
const fitFont=()=>state.autoFit?Math.max(42,Math.min(state.fontSize,92-Math.max(0,state.title.length-52)*1.05)):state.fontSize;
function upload(file,kind='image'){if(!file)return;const r=new FileReader();r.onload=()=>{const item={id:crypto.randomUUID(),name:file.name,url:r.result,kind};kind==='logo'?(state.logos.unshift(item),set({logo:item.url,logoShow:true})):(state.media.unshift(item),set({image:item.url}))};r.readAsDataURL(file)}
function autoDesign(){let[,w]=sizes[state.size];set({fontSize:state.title.length>85?54:state.title.length>55?66:82,lineHeight:state.title.length>70?1.06:1.12,overlay:state.template==='full'?58:30,badgeShow:/عاجل|طارئ|هام|مصادر/.test(state.title),imageZoom:1.08,logoX:w-300,logoY:70})}
function reset(){set({template:'classic',fontSize:76,lineHeight:1.12,badgeX:76,badgeY:74,logoX:780,logoY:70,imageZoom:1,imageX:50,imageY:50,overlay:32})}
function saveProject(){localStorage.setItem('news-banner-project',JSON.stringify(state));state.saved='تم الحفظ محليًا';render()}
function exportDesign(){let node=document.getElementById('banner'),[,w,h]=sizes[state.size],copy=node.cloneNode(true);copy.style.transform='none';copy.setAttribute('xmlns','http://www.w3.org/1999/xhtml');let data='<svg xmlns="http://www.w3.org/2000/svg" width="'+w+'" height="'+h+'"><foreignObject width="100%" height="100%">'+new XMLSerializer().serializeToString(copy)+'</foreignObject></svg>';let img=new Image(),url=URL.createObjectURL(new Blob([data],{type:'image/svg+xml;charset=utf-8'}));img.onload=()=>{let c=document.createElement('canvas');c.width=w;c.height=h;let ctx=c.getContext('2d');ctx.drawImage(img,0,0);URL.revokeObjectURL(url);let mime=state.exportType==='jpg'?'image/jpeg':state.exportType==='webp'?'image/webp':'image/png';let a=document.createElement('a');a.href=c.toDataURL(mime,state.quality);a.download=`news-banner-${w}x${h}.${state.exportType==='jpg'?'jpg':state.exportType}`;a.click()};img.src=url} 
function field(label,html){return `<label>${label}${html}</label>`} function range(k,label,min=0,max=100,step=1){return field(label,`<input data-k="${k}" type="range" value="${state[k]}" min="${min}" max="${max}" step="${step}"><output>${state[k]}</output>`)} function color(k,label){return field(label,`<input data-k="${k}" type="color" value="${state[k]}">`)}
function panel(){let t=state.tab,h=`<h2>${Object.fromEntries(tabs)[t]}</h2>`; if(t==='content')h+=field('عنوان الخبر',`<textarea data-k="title">${state.title}</textarea>`)+field('النص البديل',`<input data-k="alt" value="${state.alt}">`)+field('نوع الخبر',`<select data-k="newsType">${['سياسة','اقتصاد','رياضة','عاجل','منوعات'].map(x=>`<option ${state.newsType===x?'selected':''}>${x}</option>`).join('')}</select>`)+`<button class="primary" id="auto">إنشاء التصميم</button>`;
 if(t==='image')h+=`<label class="drop">📷 اسحب وأفلت الصورة أو اختر ملفًا<input hidden id="imageFile" type="file" accept="image/*"></label>`+range('imageZoom','Zoom',1,1.8,.01)+range('imageX','Position X')+range('imageY','Position Y')+range('overlay','Overlay')+`<button data-action="clearImage">حذف الصورة</button>`;
 if(t==='title')h+=field('الخط',`<select data-k="font">${fonts.map(f=>`<option ${state.font===f?'selected':''}>${f}</option>`).join('')}</select>`)+range('fontSize','حجم الخط',38,104)+range('weight','وزن الخط',400,1000,100)+range('lineHeight','تباعد الأسطر',.9,1.4,.01)+color('textColor','لون النص')+field('',`<input data-k="autoFit" type="checkbox" ${state.autoFit?'checked':''}> Auto Fit`);
 if(t==='badge')h+=field('',`<input data-k="badgeShow" type="checkbox" ${state.badgeShow?'checked':''}> إظهار الشارة`)+field('النمط',`<select data-k="badgePreset">${badges.map(b=>`<option ${state.badgePreset===b?'selected':''}>${b}</option>`).join('')}</select>`)+field('النص',`<input data-k="badgeText" value="${state.badgeText}">`)+color('badgeBg','الخلفية')+color('badgeColor','النص')+range('badgeSize','الحجم',.7,1.5,.01)+range('badgeX','الموضع الأفقي',0,900)+range('badgeY','الموضع الرأسي',0,250);
 if(t==='logo')h+=field('',`<input data-k="logoShow" type="checkbox" ${state.logoShow?'checked':''}> إظهار الشعار`)+`<input id="logoFile" type="file" accept="image/png,image/*">`+range('logoSize','الحجم',.6,1.8,.01)+range('logoOpacity','الشفافية',.1,1,.01)+range('logoX','الموضع الأفقي',0,900)+range('logoY','الموضع الرأسي',0,250)+`<div class="thumbs">${state.logos.map(l=>`<img data-logo="${l.id}" src="${l.url}">`).join('')}</div>`;
 if(t==='colors')h+=color('bg','لون الخلفية')+color('grad','التدرج')+range('gradPower','شدة التدرج')+field('النمط',`<select data-k="pattern"><option value="grid">شبكة</option><option value="waves">موجات</option><option value="clean">نظيف</option></select>`);
 if(t==='templates')h+=`<div class="cards">${templates.map(([id,n,d])=>`<button data-template="${id}" class="${state.template===id?'chosen':''}"><b>${n}</b><small>${d}</small></button>`).join('')}</div>`;
 if(t==='sizes')h+=`<div class="cards">${Object.entries(sizes).map(([k,s])=>`<button data-size="${k}" class="${state.size===k?'chosen':''}"><b>${s[0]}</b><small>${s[1]}×${s[2]}</small></button>`).join('')}</div>`;
 if(t==='library')h+=`<input placeholder="بحث في المكتبة"><div class="library">${[...state.media,...state.logos].map(m=>`<button data-media="${m.id}"><img src="${m.url}"><span>${m.name}</span></button>`).join('')}</div>`;
 if(t==='admin')h+=`<div class="admin"><p>لوحة إدارة مبدئية للقوالب، الخطوط، الشعارات، الألوان، المقاسات، الشارات، المستخدمين والمشاريع.</p>${['إنشاء Template جديد','تحديد العناصر الثابتة','إضافة خطوط عربية','إدارة مكتبة الوسائط'].map(x=>`<button>${x}</button>`).join('')}</div>`;
 return h+(t==='content'||t==='image'?'':`<button class="primary" id="export2">تصدير التصميم</button>`)}
function canvas(){let[,w,h]=sizes[state.size], img=state.image?`background-image:linear-gradient(rgba(0,0,0,${state.overlay/100}),rgba(0,0,0,${state.overlay/100})),url(${state.image});background-size:${state.imageZoom*100}%;background-position:${state.imageX}% ${state.imageY}%`:'';return `<section id="banner" class="banner ${state.template} ${state.pattern}" style="width:${w}px;height:${h}px;transform:scale(${state.zoom});--bg:${state.bg};--grad:${state.grad};--power:${state.gradPower}%;font-family:${state.font}"><div class="safe"></div>${state.template!=='classic'?`<div class="photo full-photo" style="${img}">${state.image?'':'اسحب الصورة أو ارفعها من لوحة التحكم'}</div>`:`<div class="photo main-photo" style="${img}">${state.image?'':'منطقة الصورة الرئيسية'}</div>`}${state.badgeShow?`<div class="badge" style="right:${state.badgeX}px;top:${state.badgeY}px;background:${state.badgeBg};color:${state.badgeColor};transform:scale(${state.badgeSize})">${state.badgeText}</div>`:''}${state.logoShow?`<div class="logo" style="right:${state.logoX}px;top:${state.logoY}px;opacity:${state.logoOpacity};transform:scale(${state.logoSize})">${state.logo?`<img src="${state.logo}">`:'<b>شعارك</b>'}</div>`:''}<div class="headline-box"><p style="font-size:${fitFont()}px;font-weight:${state.weight};line-height:${state.lineHeight};text-align:${state.align};color:${state.textColor}">${state.title}</p></div><div class="ticker">هوية إخبارية موحدة · قالب قابل للتصدير · مساحة آمنة</div></section>`}
function render(){let[,w,h]=sizes[state.size];root.innerHTML=`<div class="app" dir="rtl"><header><strong>News Banner Studio <span>استوديو البنرات الإخبارية</span></strong><nav><button id="reset">↻ مشروع جديد</button><button id="save">💾 حفظ</button><button id="export">⬇ تصدير</button></nav></header><aside class="sidebar">${tabs.map(([id,n])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}">${n}</button>`).join('')}</aside><main class="stage"><div class="toolbar"><button id="autoTop">✨ تصميم تلقائي</button><button id="zin">＋</button><button id="zout">－</button><button id="fit">ملاءمة الشاشة</button></div><div class="canvas-wrap">${canvas()}</div></main><aside class="panel">${panel()}</aside><footer><span>${w} × ${h}px</span><span>التكبير ${Math.round(state.zoom*100)}%</span><span>${state.saved}</span><button id="exportFoot">تصدير سريع</button></footer></div>`;bind()}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>set({tab:b.dataset.tab}));document.querySelectorAll('[data-k]').forEach(el=>el.oninput=e=>set({[el.dataset.k]:el.type==='checkbox'?el.checked:el.type==='range'||el.type==='number'?+el.value:el.value}));document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>set({template:b.dataset.template}));document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>set({size:b.dataset.size}));['auto','autoTop'].forEach(id=>{let x=document.getElementById(id);if(x)x.onclick=autoDesign});['export','export2','exportFoot'].forEach(id=>{let x=document.getElementById(id);if(x)x.onclick=exportDesign});document.getElementById('save').onclick=saveProject;document.getElementById('reset').onclick=reset;document.getElementById('zin').onclick=()=>set({zoom:Math.min(.8,state.zoom+.05)});document.getElementById('zout').onclick=()=>set({zoom:Math.max(.22,state.zoom-.05)});document.getElementById('fit').onclick=()=>set({zoom:.44});let im=document.getElementById('imageFile');if(im)im.onchange=e=>upload(e.target.files[0]);let lo=document.getElementById('logoFile');if(lo)lo.onchange=e=>upload(e.target.files[0],'logo');document.querySelector('[data-action="clearImage"]')?.addEventListener('click',()=>set({image:''}))}
render();
